<?php
	$number = $_POST['n'];
	if (($number < 0) || ($number > 10)){
		echo "Trebuie să alegi un număr între 1 și 10!";
	} else {
		$v1 = array("zero", "unu", "doi", "trei", "patru", "cinci", "şase", "şapte", "opt", "nouă", "zece", "unsprezece", "doisprezece", "treisprezece", "paisprezece", "cincisprezece", "şaisprezece", "şaptesprezece", "optsprezece", "nouăsprezece", "douăzeci", "douăzeci şi unu", "douăzeci şi doi", "douăzeci şi trei", "douăzeci şi patru", "douăzeci şi cinci", "douăzeci şi şase", "douăzeci şi şapte", "douăzeci şi opt", "douăzeci şi nouă", "treizeci", "treizeci şi unu", "treizeci şi doi", "treizeci şi trei", "treizeci şi patru", "treizeci şi cinci", "treizeci şi şase", "treizeci şi şapte", "treizeci şi opt", "treizeci şi nouă", "patruzeci", "patruzeci şi unu", "patruzeci şi doi", "patruzeci şi trei", "patruzeci şi patru", "patruzeci şi cinci", "patruzeci şi şase", "patruzeci şi şapte", "patruzeci şi opt", "patruzeci şi nouă", "cincizeci", "cincizeci şi unu", "cincizeci şi doi", "cincizeci şi trei", "cincizeci şi patru", "cincizeci şi cinci", "cincizeci şi şase", "cincizeci şi şapte", "cincizeci şi opt", "cincizeci şi nouă", "şaizeci", "şaizeci şi unu", "şaizeci şi doi", "şaizeci şi trei", "şaizeci şi patru", "şaizeci şi cinci", "şaizeci şi şase", "şaizeci şi şapte", "şaizeci şi opt", "şaizeci şi nouă", "şaptezeci", "şaptezeci şi unu", "şaptezeci şi doi", "şaptezeci şi trei", "şaptezeci şi patru", "şaptezeci şi cinci", "şaptezeci şi şase", "şaptezeci şi şapte", "şaptezeci şi opt", "şaptezeci şi nouă", "optzeci", "optzeci şi unu", "optzeci şi doi", "optzeci şi trei", "optzeci şi patru", "optzeci şi cinci", "optzeci şi şase", "optzeci şi şapte", "optzeci şi opt", "optzeci şi nouă", "nouăzeci", "nouăzeci şi unu", "nouăzeci şi doi", "nouăzeci şi trei", "nouăzeci şi patru", "nouăzeci şi cinci", "nouăzeci şi şase", "nouăzeci şi şapte", "nouăzeci şi opt", "nouăzeci şi nouă", "o sută");
		$v2 = array("nul", "een", "twee", "drie", "vier", "vijf", "zes", "zeven", "acht", "negen", "tien", "elf", "twaalf", "dertien", "veertien", "vijftien", "zestien", "zeventien", "achttien", "negentien", "twintig", "eenentwintig", "tweeëntwintig", "drieëntwintig", "vierëntwintig", "vijfëntwintig", "zesëntwintig", "zevenëntwintig", "achtëntwintig", "negenëntwintig", "dertig", "eenëndertig", "tweeëndertig", "drieëndertig", "vierëndertig", "vijfëndertig", "zesëndertig", "zevenëndertig", "achtëndertig", "negenëndertig", "veertig", "eenënveertig", "tweeënveertig", "drieënveertig", "vierënveertig", "vijfënveertig", "zesënveertig", "zevenënveertig", "achtënveertig", "negenënveertig", "vijftig", "eenënvijftig", "tweeënvijftig", "drieënvijftig", "vierënvijftig", "vijfënvijftig", "zesënvijftig", "zevenënvijftig", "achtënvijftig", "negenënvijftig", "zestig", "eenënzestig", "tweeënzestig", "drieënzestig", "vierënzestig", "vijfënzestig", "zesënzestig", "zevenënzestig", "achtënzestig", "negenënzestig", "zeventig", "eenënzeventig", "tweeënzeventig", "drieënzeventig", "vierënzeventig", "vijfënzeventig", "zesënzeventig", "zevenënzeventig", "achtënzeventig", "negenënzeventig", "tachtig", "eenëntachtig", "tweeëntachtig", "drieëntachtig", "vierëntachtig", "vijfëntachtig", "zesëntachtig", "zevenëntachtig", "achtëntachtig", "negenëntachtig", "negentig", "eenënnegentig", "tweeënnegentig", "drieënnegentig", "vierënnegentig", "vijfënnegentig", "zesënnegentig", "zevenënnegentig", "achtënnegentig", "negenënnegentig", "honderd");
		for ($i = 0; $i <= 10; $i++){
			$rezultat = $number + $i;
			echo "$number"; echo" + ";echo "$i"; echo" = ";echo"$rezultat<br/>";
			echo "$v1[$number]";echo" + ";echo"$v1[$i]";echo" = ";echo"$v1[$rezultat]<br/>";
			echo "$v2[$number]";echo" + ";echo"$v2[$i]";echo" = ";echo"$v2[$rezultat]<br/>";
		}
	}



